name: cd

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write   # REQUIRED for Workload Identity Federation

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: notely-483004
      REGION: us-central1
      REPO: notely-ar-repo
      IMAGE: notely
      SERVICE: notely

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Build Application
        run: ./scripts/buildprod.sh

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/249324394764/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: cloud-run-deployer@notely-483004.iam.gserviceaccount.com

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Trigger Cloud Build
        run: gcloud builds submit --config=cloudbuild.yaml --project=notely-483004
