name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Force Failure
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

      - name: Run gosec Check
        run: gosec ./...
        
  Style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25.1"

      - name: Run gofmt
        run: |
          UNFORMATTED=$(gofmt -l . | sed '/^vendor\//d')
          if [ -n "$UNFORMATTED" ]; then
            echo "The following files are not properly formatted:"
            echo "$UNFORMATTED"
          fi
          # Fail if any non-vendor files are unformatted
          test -z "$UNFORMATTED"
          # Also run go fmt on all packages
          go fmt ./...
      
      - name: Install Staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run Staticcheck
        run: staticcheck ./...